/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sourabh
 */
public class Home_page extends javax.swing.JFrame {
 String username = "";
    public void setusername(String user){
    username = user;
    comment.setText("Welcome to Algorithma " + username);
    }
    /**
     * Creates new form Home_page
     */
    public Home_page() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comment = new javax.swing.JLabel();
        da = new javax.swing.JButton();
        pri = new javax.swing.JButton();
        insertion_sort = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        comment.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        comment.setForeground(new java.awt.Color(0, 51, 51));

        da.setBackground(new java.awt.Color(51, 51, 0));
        da.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        da.setForeground(new java.awt.Color(204, 204, 255));
        da.setText("Dijkstra Algorithm");
        da.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                daMouseClicked(evt);
            }
        });

        pri.setBackground(new java.awt.Color(102, 0, 255));
        pri.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        pri.setForeground(new java.awt.Color(153, 255, 153));
        pri.setText("Prims Algorithm");
        pri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                priMouseClicked(evt);
            }
        });

        insertion_sort.setBackground(new java.awt.Color(204, 0, 51));
        insertion_sort.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        insertion_sort.setForeground(new java.awt.Color(255, 255, 255));
        insertion_sort.setText("insertion sort");
        insertion_sort.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                insertion_sortMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(comment))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(da, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(insertion_sort, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(280, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(comment)
                .addGap(110, 110, 110)
                .addComponent(da, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(pri, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(insertion_sort, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Dijkstar1 dij = new Dijkstar1();
    private void daMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_daMouseClicked
       dij.setVisible(true);
    }//GEN-LAST:event_daMouseClicked
    prims pr = new prims();
    private void priMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_priMouseClicked
        pr.setVisible(true);
    }//GEN-LAST:event_priMouseClicked
    insertionsort insert = new insertionsort();
    private void insertion_sortMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_insertion_sortMouseClicked
        insert.setVisible(true);
    }//GEN-LAST:event_insertion_sortMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home_page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home_page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel comment;
    private javax.swing.JButton da;
    private javax.swing.JButton insertion_sort;
    private javax.swing.JButton pri;
    // End of variables declaration//GEN-END:variables
    
}
