/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.*;

/**
 *
 * @author sourabh
 */
public class Log_in extends javax.swing.JFrame {
    int flag =0;

    /**
     * Creates new form Sign_up
     */
    public Log_in() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Textfield_username = new javax.swing.JTextField();
        Passwordfield_password = new javax.swing.JPasswordField();
        Log_in_Button = new javax.swing.JButton();
        Sign_up_Button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Username = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        comment = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Textfield_username.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        Textfield_username.setForeground(new java.awt.Color(102, 102, 102));
        Textfield_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Textfield_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Textfield_usernameFocusLost(evt);
            }
        });
        Textfield_username.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Textfield_usernameKeyPressed(evt);
            }
        });

        Passwordfield_password.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        Passwordfield_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                Passwordfield_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                Passwordfield_passwordFocusLost(evt);
            }
        });

        Log_in_Button.setBackground(new java.awt.Color(51, 51, 0));
        Log_in_Button.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        Log_in_Button.setForeground(new java.awt.Color(204, 204, 255));
        Log_in_Button.setText("Log-in");
        Log_in_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Log_in_ButtonMouseClicked(evt);
            }
        });

        Sign_up_Button.setBackground(new java.awt.Color(102, 0, 255));
        Sign_up_Button.setFont(new java.awt.Font("Rockwell", 3, 18)); // NOI18N
        Sign_up_Button.setForeground(new java.awt.Color(153, 255, 153));
        Sign_up_Button.setText("Sign-up");
        Sign_up_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Sign_up_ButtonMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 2, 18)); // NOI18N
        jLabel1.setForeground(java.awt.Color.red);
        jLabel1.setText("( Not a member yet ! sign up )");

        Username.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        Username.setText("Username");

        Password.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        Password.setText("Password");

        comment.setFont(new java.awt.Font("Cambria", 3, 18)); // NOI18N
        comment.setForeground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Password)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(Log_in_Button))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Textfield_username, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(Passwordfield_password)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(Sign_up_Button))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(comment)))
                .addContainerGap(255, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Textfield_username, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Passwordfield_password, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(Log_in_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Sign_up_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(comment)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    Home_page home = new Home_page();
    private void Log_in_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Log_in_ButtonMouseClicked
       try{
           Connection myconn = DriverManager.getConnection("jdbc:mysql://Localhost:3306/algorithma?autoReconnect=true&useSSL=false","root","Sourabh@67");
           Statement stmt = myconn.createStatement();
           ResultSet rs = stmt.executeQuery("select * from members");
           while(rs.next()){
              String user = rs.getString("username");
              String pass = rs.getString("password");
              
               if(user.equals(Textfield_username.getText()) && pass.equals(Passwordfield_password.getText())){
                    home.setusername(user);
                    home.setVisible(true);
                    flag = 1;
                }
           }
           
           if(flag == 0){
               comment.setText(" ( User doesn't exist ! ) ");
               
           }
           if(Textfield_username.getText().equals("") || Passwordfield_password.getText().equals("")){
               comment.setText(" ( username or password can't be empty ) ");
           }
        }
        catch(Exception e){
            e.printStackTrace();
        }    
    }//GEN-LAST:event_Log_in_ButtonMouseClicked
    Sign_up sign_up = new Sign_up();
    private void Sign_up_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Sign_up_ButtonMouseClicked
        sign_up.setVisible(true);
    }//GEN-LAST:event_Sign_up_ButtonMouseClicked

    private void Textfield_usernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Textfield_usernameKeyPressed
            comment.setText("");
    }//GEN-LAST:event_Textfield_usernameKeyPressed

    private void Textfield_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Textfield_usernameFocusGained
            Textfield_username.setBackground(new java.awt.Color(0, 255, 204));
    }//GEN-LAST:event_Textfield_usernameFocusGained

    private void Textfield_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Textfield_usernameFocusLost
            Textfield_username.setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_Textfield_usernameFocusLost

    private void Passwordfield_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Passwordfield_passwordFocusGained
           Passwordfield_password.setBackground(new java.awt.Color(204,204,255));
    }//GEN-LAST:event_Passwordfield_passwordFocusGained

    private void Passwordfield_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Passwordfield_passwordFocusLost
           Passwordfield_password.setBackground(new java.awt.Color(255,255,255));
    }//GEN-LAST:event_Passwordfield_passwordFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Log_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Log_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Log_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Log_in.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Log_in().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Log_in_Button;
    private javax.swing.JLabel Password;
    private javax.swing.JPasswordField Passwordfield_password;
    private javax.swing.JButton Sign_up_Button;
    private javax.swing.JTextField Textfield_username;
    private javax.swing.JLabel Username;
    private javax.swing.JLabel comment;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
   
}
